version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    groups:
      typescript-tooling:
        patterns:
          - "typescript"
          - "@types/*"
          - "ts-node"
      iobroker-tooling:
        patterns:
          - "@iobroker/*"
      test-tooling:
        patterns:
          - "mocha"
          - "chai"
          - "sinon*"
          - "@types/mocha"
          - "@types/chai*"
          - "@types/sinon*"
          - "proxyquire"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Berlin"
    labels:
      - "dependencies"
      - "github-actions"
